# Generated by Django 5.0.6 on 2024-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('followers', models.IntegerField()),
                ('audience_country', models.CharField(max_length=200)),
                ('aut_eng', models.IntegerField()),
                ('avg_eng', models.IntegerField()),
            ],
        ),
    ]
